name: Release

on:
  push:
    branches:
      - "release"
      - "main"

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci --force

      - run: cp example.vars.json vars.json
      - run: cp .env.exemple .env
      - run: npm run build
      - run: tar -czvf joona-meet.tar.gz dist package.json package-lock.json
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
